# Generated by Django 3.2.7 on 2021-09-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_game_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='purchaser',
            new_name='owner',
        ),
    ]
